"""minutes

Revision ID: af6b2aa1225b
Revises: b8ffad393b46
Create Date: 2018-03-23 21:00:46.837645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6b2aa1225b'
down_revision = 'b8ffad393b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minutes',
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('vsell', sa.Float(), nullable=True),
    sa.Column('vbuy', sa.Float(), nullable=True),
    sa.Column('nsell', sa.Integer(), nullable=True),
    sa.Column('nbuy', sa.Integer(), nullable=True),
    sa.Column('ratesell', sa.Float(), nullable=True),
    sa.Column('ratebuy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('market', 'timestamp')
    )
    op.create_index('idx_timestamp', 'trades', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_timestamp', table_name='trades')
    op.drop_table('minutes')
    # ### end Alembic commands ###
